#cloud-config
hostname: ##HostName##

fqdn: ##FQDN##

write_files:
- path: /etc/netplan/50-cloud-init.yaml
  content: |
    network:
     version: 2
     ethernets:
      ens192:
       addresses: ##IPAddressCIDR##

       gateway4: ##Gateway##
       dhcp6: false
       nameservers:
         addresses:
           - ##DNSServer1##
         search:
           - ##DNSSearchDomain##
       dhcp4: false
       optional: true
- path: /etc/sysctl.d/60-disable-ipv6.conf
  owner: root
  content: |
    net.ipv6.conf.all.disable_ipv6=1
    net.ipv6.conf.default.disable_ipv6=1
    net.ipv6.conf.lo.disable_ipv6=1
- path: /root/disable_ipv6.sh
  permissions: 0744
  owner: root
  content: |
    #!/usr/bin/env bash
    set -e
    echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
    echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
    echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf
- path: /etc/hosts
  content: 127.0.0.1 ##HostName##

  append: true
- path: /etc/cron.hourly/oc_cleanup
  owner: root
  permissions: '0777'
  content: "mysql -u ocuser -D opencart -e 'delete from oc_session where oc_session.expire < DATE_SUB(NOW(), INTERVAL 360 DAY);'"
- path: /etc/cron.daily/mysqlslowlogs
  owner: root
  permissions: '0666'
  content: |
        /var/lib/mysql/mysql-slow.log {
        size 1G
        dateext
        compress
        missingok
        rotate 2
        notifempty
        delaycompress
        sharedscripts
        nocopytruncate
        create 660 mysql mysql
        postrotate
        /usr/bin/mysql -e 'select @@global.slow_query_log into @sq_log_save; set global slow_query_log=off; select sleep(5); FLUSH SLOW LOGS; select sleep(10); set global slow_query_log=@sq_log_save;'
        endscript
        rotate 150
        }

- path: /etc/holodeck/90-sdn-lab.yaml
  content: |
    network:
     version: 2
     ethernets:
      ens192:
       addresses: ##IPAddressCIDR##
       gateway4: ##Lab-Gateway##
       dhcp6: false
       nameservers:
         addresses:
           - ##DNSServer1##
         search:
           - ##DNSSearchDomain##
       dhcp4: false
       optional: true
- path: /etc/holodeck/sdn-lab-prepare.sh
  owner: root
  permissions: 0777
  content: |
    #!/bin/bash
    set -v
    sudo touch /etc/cloud/cloud-init.disabled
    sudo rm -rf /etc/netplan/50-cloud-init.yaml
    sudo mv /etc/holodeck/90-sdn-lab.yaml /etc/netplan/10-sdn-lab.yaml
    #shutdown
    sudo shutdown -h now


runcmd:
- bash /root/disable_ipv6.sh
- netplan --debug apply
- sysctl -w net.ipv6.conf.all.disable_ipv6=1
- sysctl -w net.ipv6.conf.default.disable_ipv6=1
- sysctl -w net.ipv6.conf.lo.disable_ipv6=1
- apt-get -y clean
- apt-get -y autoremove --purge
# Begin Jim's opencart insert
- export DEBIAN_Apache=noninteractive
- export USER="ocuser"
- export PASS="VMware123!"
- echo $USER:$PASS | /usr/sbin/chpasswd
- sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
- service ssh reload
#Begin MySQL specific customizations
- echo "mysql-server-5.7 mysql-server/root_password password root" | sudo debconf-set-selections
- echo "mysql-server-5.7 mysql-server/root_password_again password root" | sudo debconf-set-selections
- echo "[client]" >> /etc/mysql/mysql.conf.d/mysqld.cnf
- echo "user=root" >> /etc/mysql/mysql.conf.d/mysqld.cnf
- echo "password=root" >> /etc/mysql/mysql.conf.d/mysqld.cnf
- echo "user=ocuser" >> /etc/mysql/mysql.conf.d/mysqld.cnf
- echo "password=$PASS" >> /etc/mysql/mysql.conf.d/mysqld.cnf
- sed -i 's/#slow/slow/g' /etc/mysql/mysql.conf.d/mysqld.cnf
- sed -i 's/#long_query_time/long_query_time/g' /etc/mysql/mysql.conf.d/mysqld.cnf
- sed -i 's/bind-address/#bind-address/g' /etc/mysql/mysql.conf.d/mysqld.cnf
- systemctl restart mysql
- mysql -u root -e "GRANT ALL ON *.* TO '$USER'@'%' IDENTIFIED BY '$PASS'"
- mysql -u root -e 'CREATE DATABASE opencart'
- mysql -u root -e 'USE opencart'
- mysql -u root -e 'flush privileges'
- cd /tmp
- echo 'Cloud-init is done!' >> /tmp/finished.txt
#End MySQL specific config

packages:
  - apache2
  - php
  - php-mysql
  - libapache2-mod-php
  - php-cli
  - php-common
  - php-intl
  - php-gd
  - php-mbstring
  - php-xml
  - php-zip
  - php-curl
  - php-xmlrpc
  - mysql-server-5.7
  - mysql-client
  - unzip
  - open-vm-tools
timezone: America/Chicago
system_info:
  default_user:
    name: default-user
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
disable_root: false
ssh_pwauth: yes
# requires mkpasswd command (whois package)
# SHA-512 Rounds 4096

users:
  - default
  - name: cloudadmin
    gecos: Cloud
    lock_passwd: false
    groups: sudo, users, admin
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
  - name: ocuser
    gecos: Opencart User
    lock_passwd: false
    groups: sudo, users, admin
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    #password: $6$rounds=4096$L2g1RTFocPEW$u.VUUpZKxik.Mr8l4XrZRAC5o0xiiNiWBy9gx.Vy5IkQxeIMAvzCbk2kU6yRHJhzMvdMSJ/VaStqoupJqkBfS0
    #expire: false

    #ssh_authorized_keys:
    #- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQClyiDSR+D7zweN1Hul0RwT8l5dcElrUE7BC/dODifVBeyN4XQHVTE4OUIlD6WStPfUcJudnrER08ec7YXjB3wjcxH+N5xiRaHMAh2WDONY4bWF5iVrbmM7joJmg35/sLQC6kdb3tHrgHQ4aBuel9xAKQBCpy1AGMI8isaAJpAghaubsAmQI9suc+ba8kqeUbqjgfTeFPwjNTLMhQjD6Fn/qOgcdbxa6srs5KnMeCOLgCM6kSN5+fy7T4E1VMDjkKA1DCvZN2I0/9CJQCEowtkBo086s3GI3btU3GeKmnoVS9D0EFMyvN8Axyw90qd/Q2QQMF21XKFHq5bTJ9O0rXVIW9eoJpCgOLn+Y1kj8lIkVd/rFKEIm5C6OrdcdlsAGFmhwHTdbU7ZylpuuUqlymeYrZkmUISzkkoWxOCao0nkcPnoV0fEZ7wnW/xuEsqjSq+76JTE2tPsKRu2Q0nUa5l360clhRjvR/MVGqvWLomLvm0yGkax8ZKCXENo29yWW13RGHnYgQgRkPFACqe47zisHWeATOZ2ms9Ev05gBTK9N92y3bWarWTsZ4gl8IY1GWcaNGb0lPaCZBui8Qbi1UdbzqGJhURtOwLoO9/GZB2s5irpwgyBqfWUBqmQSX3BBexE0eIuLSEEcz2pq/aMI/trCmp4uuaLQz93v3vkwHmiVQ== lucd@local.lab
chpasswd:
  list: |
    default-user: $6$rounds=4096$L2g1RTFocPEW$u.VUUpZKxik.Mr8l4XrZRAC5o0xiiNiWBy9gx.Vy5IkQxeIMAvzCbk2kU6yRHJhzMvdMSJ/VaStqoupJqkBfS0
    ocuser: $6$rounds=4096$L2g1RTFocPEW$u.VUUpZKxik.Mr8l4XrZRAC5o0xiiNiWBy9gx.Vy5IkQxeIMAvzCbk2kU6yRHJhzMvdMSJ/VaStqoupJqkBfS0
    cloudadmin: $6$rounds=4096$L2g1RTFocPEW$u.VUUpZKxik.Mr8l4XrZRAC5o0xiiNiWBy9gx.Vy5IkQxeIMAvzCbk2kU6yRHJhzMvdMSJ/VaStqoupJqkBfS0
  expire: false
package_upgrade: true
package_reboot_if_required: true
power_state:
  delay: now
  mode: reboot
  message: Rebooting the OS
  condition: if [ -e /var/run/reboot-required ]; then exit 0; else exit 1; fi
